<a href="https://colab.research.google.com/github/zamman365-glitch/Libraries/blob/main/Pandas_class8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas - Class 8: Working with Time Series
Welcome to **Class 8** of our Pandas series. Today we’ll learn how to handle and analyze time series data.

## 1. Converting Columns to Datetime (`pd.to_datetime`)
- Use `pd.to_datetime()` to convert strings or numbers into datetime objects.
- Once converted, Pandas recognizes them as dates, enabling powerful operations.

In [ ]:
import pandas as pd

# 1. Create the dataset
data = {
    "OrderID": [1001, 1002, 1003, 1004, 1005],
    "OrderDate": ["2024-01-05", "2024/01/12", "15-01-2024", "2024-01-20", "20240125"],
    "Customer": ["Alice", "Bob", "Charlie", "David", "Emma"],
    "Amount": [250, 400, 150, 300, 500]
}
df = pd.DataFrame(data)
df

   OrderID   OrderDate Customer  Amount
0     1001  2024-01-05    Alice     250
1     1002  2024/01/12      Bob     400
2     1003  15-01-2024  Charlie     150
3     1004  2024-01-20    David     300
4     1005    20240125     Emma     500

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   OrderID    5 non-null      int64
 1   OrderDate  5 non-null      object
 2   Customer   5 non-null      object
 3   Amount     5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [ ]:
df["OrderDate"] = pd.to_datetime(df["OrderDate"],format="mixed",errors="coerce")
df

   OrderID  OrderDate Customer  Amount
0     1001 2024-01-05    Alice     250
1     1002 2024-01-12      Bob     400
2     1003 2024-01-15  Charlie     150
3     1004 2024-01-20    David     300
4     1005 2024-01-25     Emma     500

In [ ]:
df["OrderDate"] = pd.to_datetime(df["OrderDate"],format="mixed",errors="coerce")
df

   OrderID  OrderDate Customer  Amount
0     1001 2024-01-05    Alice     250
1     1002 2024-01-12      Bob     400
2     1003 2024-01-15  Charlie     150
3     1004 2024-01-20    David     300
4     1005 2024-01-25     Emma     500

In [ ]:
pd.to_datetime(df["OrderDate"],format="mixed",errors="coerce").dt.strftime("%d-%m-%y")

0    05-01-24
1    12-01-24
2    15-01-24
3    20-01-24
4    25-01-24
Name: OrderDate, dtype: object

## 2. Setting DateTime Index & Resampling
- Set a datetime column as the index with `set_index()`.
- Resample time series using `resample('M').mean()` or other rules ('D', 'W', 'Y').
- Useful for aggregating data by time periods.

In [ ]:
print(df)

   OrderID  OrderDate Customer  Amount
0     1001 2024-01-05    Alice     250
1     1002 2024-01-12      Bob     400
2     1003 2024-01-15  Charlie     150
3     1004 2024-01-20    David     300
4     1005 2024-01-25     Emma     500

In [ ]:
# step 1 :- OrderDate set as index
df_idx = df.set_index("OrderDate")
df_idx

            OrderID Customer  Amount
OrderDate
2024-01-05     1001    Alice     250
2024-01-12     1002      Bob     400
2024-01-15     1003  Charlie     150
2024-01-20     1004    David     300
2024-01-25     1005     Emma     500

In [ ]:
# step 2:- We will resample complete data
# according to months and we will get the total
# ammount of that month

monthly_sales = df_idx.resample("M")['Amount'].sum()
monthly_sales

/tmp/ipykernel_3253/931385691.py:5: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  monthly_sales = df_idx.resample("M")['Amount'].sum()

OrderDate
2024-01-31    1600
Freq: ME, Name: Amount, dtype: int64

In [ ]:
year_average = df_idx.resample("Y")['Amount'].mean()
year_average

/tmp/ipykernel_3253/1692281093.py:1: FutureWarning: 'Y' is deprecated and will be removed in a future version, please use 'YE' instead.
  year_sales = df_idx.resample("Y")['Amount'].mean()

OrderDate
2024-12-31    320.0
Freq: YE-DEC, Name: Amount, dtype: float64

In [ ]:
week_average = df_idx.resample("W")['Amount'].mean()
week_average

OrderDate
2024-01-07    250.0
2024-01-14    400.0
2024-01-21    225.0
2024-01-28    500.0
Freq: W-SUN, Name: Amount, dtype: float64

## mini-project

Converting columns to datetime (pd.to_datetime)

Setting a DateTime index & resampling

In [ ]:

# 1️⃣ Create a dataset of website visits (string dates + visit counts)

# 2️⃣ Convert VisitDate to datetime
# Write your code here

# 3️⃣ Set VisitDate as the index
# Write your code here

# 4️⃣ Resample to get total visitors per month
# Write your code here

# 5️⃣ Resample to get average visitors per week
# Write your code here

In [ ]:
# 1️⃣ Create a dataset of website visits (string dates + visit counts)
data = {
    "VisitDate": ["2023-01-01", "2023-01-0", "2023-01-03", "2023-01-04", "2023-01-05"],
    "Visits": [10, 15, 20, 25, 30]
}

---
## Summary
- Converted columns to datetime with `pd.to_datetime`.
- Set DateTime index and resampled data.
- Performed date-based filtering and slicing.
- Applied rolling and expanding window calculations.