<a href="https://colab.research.google.com/github/zamman365-glitch/Libraries/blob/main/pandas_class4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🐼 Pandas - Class 4: Data Selection & Filtering
Welcome to **Class 4** of our Pandas series. Today we’ll explore techniques to select and filter data in a DataFrame.

## 1. Boolean Indexing & Conditional Selection
- Use comparison operators to build conditions (e.g., `df['col'] > 50`).
- Pass the condition inside `df[...]` to get matching rows.
- Combine multiple conditions with `&` (AND), `|` (OR), and `~` (NOT).
- Parentheses are required when combining conditions.

In [18]:
import pandas as pd

a ={
    "Name":['Devraj','Bob','Charlie','David','Emma'],
    'Age':[25,30,35,40,22],
    'Score':[80,92,79,85,95]

    }

b=pd.DataFrame(a)

#1. Selecting single column
b[b['Age'] > 27]


#2. Selecting single column Score > 85
b[b['Score']>85]


#3. Multiple Conditions (AND) : Age > 27 AND Score > 85
b[(b['Age'] > 27) & (b['Score']>85)]
# jab kabhi bhi multiple condition apply karenge dataframe mei toh () use karenge


#4. Multiple Conditions (OR) : Age > 27 OR Score > 85
b[(b['Age'] > 27) | (b['Score']>85)]

#5.NOT (~)
b[~(b['Score']>85)]

#6. Age > 22 and Score >80
b[(b['Age'] > 22) & (b['Score']>80)]

    Name  Age  Score
1    Bob   30     92
3  David   40     85

## 2. Filtering Rows with Multiple Conditions
- Combine two or more conditions to refine selection.
- Remember to enclose each condition in parentheses.

In [22]:
#1. Age > 25 AND Score >85
b[(b['Age'] > 25) & (b['Score']>85)]
#2. Age < 35 or Score >=90
b[(b['Age'] < 35) | (b['Score']>=90)]
#3. Age between 25 and 35 (inclusive)
b[(b['Age'] >= 25) & (b['Age']<=35)]

      Name  Age  Score
0   Devraj   25     80
1      Bob   30     92
2  Charlie   35     79

## 3. Using `query()` for Cleaner Filtering
- `query()` allows filtering rows with a string expression.
- It's concise and readable for complex conditions.
- Variables can be passed using the `@` symbol.

In [27]:
#1. Simple Query : Age >25
print(b.query("Age >25"))

#2. MUltiple Conditions using query: Age <35 and Score >=85
print(b.query("Age < 35 and Score >=85"))


#3. MUltiple Conditions using query: Age >30 and Score >=90
print(b.query("Age >= 30 and Score >=90"))


#4.Threshold
#2. @-> Threshold
score=90 # Variables
print(b.query("Score>=@score"))

      Name  Age  Score
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
   Name  Age  Score
1   Bob   30     92
4  Emma   22     95
  Name  Age  Score
1  Bob   30     92
   Name  Age  Score
1   Bob   30     92
4  Emma   22     95

## 4. String Operations on Columns
- Use the `.str` accessor for vectorized string methods.
- Common methods: `contains`, `replace`, `startswith`, `endswith`, `lower`, `upper`.
- Useful for cleaning or filtering text data.

In [40]:
print(b)

#1.Convert name to lowercase().
print(b['Name'].str.lower())


#2.Convert name to uppercase().
print(b['Name'].str.upper())


#3. Title()
print(b['Name'].str.title())


#4. Replace a substring('OldString','NewString')
print(b['Name'].str.replace('Charlie','Charles'))


#5. contains -> Check if name contains the letter 'a'
b[b['Name'].str.contains('a')]


#6. .startswith('Letter') -> Letter starting with
b[b['Name'].str.startswith('D')]


#7. .endswith('Letter')
b[b['Name'].str.endswith('b')]

      Name  Age  Score
0   Devraj   25     80
1      Bob   30     92
2  Charlie   35     79
3    David   40     85
4     Emma   22     95
0     devraj
1        bob
2    charlie
3      david
4       emma
Name: Name, dtype: object
0     DEVRAJ
1        BOB
2    CHARLIE
3      DAVID
4       EMMA
Name: Name, dtype: object
0     Devraj
1        Bob
2    Charlie
3      David
4       Emma
Name: Name, dtype: object
0     Devraj
1        Bob
2    Charles
3      David
4       Emma
Name: Name, dtype: object

  Name  Age  Score
1  Bob   30     92

## Mini Practice
1. Build a DataFrame with columns such as Name, Age, City, Score.
2. Use boolean indexing to select rows where Age > 25.
3. Filter rows where City is either 'Delhi' or 'Mumbai'.
4. Use query() to find rows with Score >= 85 and Age < 35.
5. Clean a text column using str.replace or str.lower.

In [ ]:


# 1. Build a DataFrame with columns: Name, Age, City, Score


# 2. Use boolean indexing to select rows where Age > 25
# Write your code here

# 3. Filter rows where City is either 'Delhi' or 'Mumbai'
# Write your code here

# 4. Use query() to find rows with Score >= 85 and Age < 35
# Write your code here

# 5. Clean a text column using str.replace or str.lower
# Example: convert City names to lowercase or replace "delhi" with "New Delhi"
# Write your code here

---
## Summary
- Learned to use boolean indexing and conditional selection.
- Filtered rows with multiple conditions.
- Used `query()` for clean filtering.
- Applied string operations with the `.str` accessor.