<a href="https://colab.research.google.com/github/zamman365-glitch/Libraries/blob/main/pandas_class4_assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Pandas Class 4 Assignment


# Q1. Select Single Column

## Problem Statement
Create a DataFrame and display only the Name column.

## Sample Input
```python
Name, Age
```

## Sample Output
```python
Only Name column
```

In [3]:
# Write your code here
import pandas as pd
data=pd.DataFrame({
    'Name':['aman','bilal','LL','Goti'],
    'Age':[20,21,7,21],
    'Marks':[90,100,79,50]
})
print(data['Name'])

0     aman
1    bilal
2       LL
3     Goti
Name: Name, dtype: object


# Q2. Select Multiple Columns

## Problem Statement
Display Name and Marks columns from a DataFrame.

## Sample Input
```python
Name, Marks
```

## Sample Output
```python
Selected columns
```

In [6]:
# Write your code here
print(data[['Name','Marks']])

    Name  Marks
0   aman     90
1  bilal    100
2     LL     98
3   Goti     50


# Q3. Filter Students

## Problem Statement
Display students with Marks greater than 80.

## Sample Input
```python
Marks > 80
```

## Sample Output
```python
Filtered rows
```

In [7]:
# Write your code here
data[data['Marks']>80]

    Name  Age  Marks
0   aman   20     90
1  bilal   21    100
2     LL    7     98


# Q4. Filter by City

## Problem Statement
Display students belonging to Bhopal.

## Sample Input
```python
City = Bhopal
```

## Sample Output
```python
Matching rows
```

In [8]:
# Write your code here
df = pd.DataFrame({
    "Name": ["Aman", "Bilal", "Rahul", "Sara"],
    "City": ["Bhopal", "Indore", "Bhopal", "Delhi"],
    "Marks": [85, 90, 78, 92]
})


print(df[df["City"] == "Bhopal"])

    Name    City  Marks
0   Aman  Bhopal     85
2  Rahul  Bhopal     78


# Q5. Find Maximum Marks

## Problem Statement
Find the highest marks from a DataFrame.

## Sample Input
```python
Marks column
```

## Sample Output
```python
Highest value
```

In [10]:
# Write your code here
df['Marks'].max()

92


# Q6. Find Minimum Age

## Problem Statement
Find the minimum age.

## Sample Input
```python
Age column
```

## Sample Output
```python
Minimum age
```

In [11]:
# Write your code here
data['Age'].min()

7


# Q7. Sort Data

## Problem Statement
Sort students by Marks.

## Sample Input
```python
Marks column
```

## Sample Output
```python
Sorted DataFrame
```

In [12]:
# Write your code here
df.sort_values(by='Marks')

    Name    City  Marks
2  Rahul  Bhopal     78
0   Aman  Bhopal     85
1  Bilal  Indore     90
3   Sara   Delhi     92


# Q8. Value Counts

## Problem Statement
Count occurrences of each city.

## Sample Input
```python
City column
```

## Sample Output
```python
Frequency count
```

In [13]:
# Write your code here
df['City'].value_counts()

City
Bhopal    2
Indore    1
Delhi     1
Name: count, dtype: int64


# Q9. Group By City

## Problem Statement
Find average marks city-wise.

## Sample Input
```python
City and Marks
```

## Sample Output
```python
Grouped result
```

In [18]:
# Write your code here
print(df.groupby("City")["Marks"].mean())

City
Bhopal    81.5
Delhi     92.0
Indore    90.0
Name: Marks, dtype: float64


# Q10. Multiple Conditions

## Problem Statement
Display students with Marks > 70 and Age > 20.

## Sample Input
```python
Marks and Age
```

## Sample Output
```python
Filtered rows
```

In [15]:
# Write your code here
data[(data['Marks']>70)&(data['Age']>20)]

    Name  Age  Marks
1  bilal   21    100